GET http://localhost:8080/api/employees
###
GET http://localhost:8080/api/employees/1
###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{"name": "John Smith"}
###
POST http://localhost:8080/api/employees/1
Content-Type: application/json

{"name": "John Doe2"}
###
